version: "3.9"
services:
  api-rest:
    container_name: code-cracker-api-rest
    build:
      context: .
      dockerfile: api-rest/Dockerfile
    ports:
      - "8124:8124"
    environment:
      - SERVER_PORT=8124

  web-cli:
    container_name: code-cracker-web-cli
    build:
      context: ./web-cli
      args:
        # pass the API endpoint via environment variable for flexible configuration
        VITE_API_BASE: ${API_ENDPOINT:-http://192.168.100.142:8124/codebreaker/v1}
    ports:
      - "8080:80"
    depends_on:
      - api-rest
networks:
  default:
    name: code-cracker-net
